# Generated by Django 3.2.7 on 2023-06-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='photo1',
            field=models.IntegerField(blank=True, null=True, verbose_name='朝の体温'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='夜の症状'),
        ),
        migrations.AddField(
            model_name='diary',
            name='photo3',
            field=models.IntegerField(blank=True, null=True, verbose_name='夜の体温'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='朝の症状'),
        ),
    ]
